events {
  worker_connections 1024;
}

http {
  upstream postgrest {
    server rest:3000;
  }

  upstream gotrue {
    server auth:9999;
  }

  server {
    listen 80;

    location /rest/v1/ {
      proxy_pass http://postgrest/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /auth/v1/ {
      proxy_pass http://gotrue/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
