/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhooksDeliveryRouteImport } from './routes/api/public/webhooks/delivery'
import { Route as ApiPublicFakePlatformPlatformPostsRouteImport } from './routes/api/public/fake-platform/$platform/posts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksDeliveryRoute =
  ApiPublicWebhooksDeliveryRouteImport.update({
    id: '/api/public/webhooks/delivery',
    path: '/api/public/webhooks/delivery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFakePlatformPlatformPostsRoute =
  ApiPublicFakePlatformPlatformPostsRouteImport.update({
    id: '/api/public/fake-platform/$platform/posts',
    path: '/api/public/fake-platform/$platform/posts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/webhooks/delivery': typeof ApiPublicWebhooksDeliveryRoute
  '/api/public/fake-platform/$platform/posts': typeof ApiPublicFakePlatformPlatformPostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/webhooks/delivery': typeof ApiPublicWebhooksDeliveryRoute
  '/api/public/fake-platform/$platform/posts': typeof ApiPublicFakePlatformPlatformPostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/webhooks/delivery': typeof ApiPublicWebhooksDeliveryRoute
  '/api/public/fake-platform/$platform/posts': typeof ApiPublicFakePlatformPlatformPostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/webhooks/delivery'
    | '/api/public/fake-platform/$platform/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/webhooks/delivery'
    | '/api/public/fake-platform/$platform/posts'
  id:
    | '__root__'
    | '/'
    | '/api/public/webhooks/delivery'
    | '/api/public/fake-platform/$platform/posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicWebhooksDeliveryRoute: typeof ApiPublicWebhooksDeliveryRoute
  ApiPublicFakePlatformPlatformPostsRoute: typeof ApiPublicFakePlatformPlatformPostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/delivery': {
      id: '/api/public/webhooks/delivery'
      path: '/api/public/webhooks/delivery'
      fullPath: '/api/public/webhooks/delivery'
      preLoaderRoute: typeof ApiPublicWebhooksDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fake-platform/$platform/posts': {
      id: '/api/public/fake-platform/$platform/posts'
      path: '/api/public/fake-platform/$platform/posts'
      fullPath: '/api/public/fake-platform/$platform/posts'
      preLoaderRoute: typeof ApiPublicFakePlatformPlatformPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicWebhooksDeliveryRoute: ApiPublicWebhooksDeliveryRoute,
  ApiPublicFakePlatformPlatformPostsRoute:
    ApiPublicFakePlatformPlatformPostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
